### ISSUE TITLE
can't sort on the column of command

### ISSUE THREAD

**Issue by tlsalex** [Nuke928/NTop#11]
I can sort on all columns except the command column
what I did exactly : sort COMMAND
It shows me unknown column: command

**Comment by Nuke928** [comment]
At one time I renamed the "EXE" column to "COMMAND" and forgot to change the sort command, my bad.

In the meanwhile you can also use CTRL+ArrowKeys to change column sort.

**Comment by tlsalex** [comment]
BTW , I prefer you use Process instead of COMMAND as column.

BR
