### ISSUE TITLE
Could you please add disk usage for each process in this program 

### ISSUE THREAD

**Issue by tlsalex** [Nuke928/NTop#3]
Hello , 

With GUI task manager , we can see CPU, memory , disk usage for each process.
But in your current program , it miss disk usage for each process,
Will it possible to add it to this program for you ?

Of course , it is still very very cool without that part to windows platform. 
Hope to have good news from you!

BR

**Comment by Nuke928** [comment]
I'll see if I can do it. My bet is using https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-getprocessiocounters but no idea if it'll work as expected.

**Comment by Nuke928** [comment]
It's now in https://github.com/Nuke928/NTop/releases/tag/v0.3.0!

**Comment by Nuke928** [comment]
Actually I forgot something and introduced a bug. Nvm.

**Comment by tlsalex** [comment]
Sorry , 
I am not a program developer, could you please compile your code into a binary executable file.
and release under you REPO.

one more things , I hear one user said that this tool only works well on cmd and has weird display in PowerShell.  Could you please also check that mater.
See here for more detail . https://github.com/PowerShell/PowerShell/issues/9452


Thank you

**Comment by Nuke928** [comment]
As soon as I fix the bug I'll release the new binary!

And I wasn't aware of that. I'll try fixing that.

**Comment by Nuke928** [comment]
https://github.com/Nuke928/NTop/releases/tag/v0.3.0
