### ISSUE TITLE
The layout is not good

### ISSUE THREAD

**Issue by tlsalex** [Nuke928/NTop#5]
The layout seems has a little mess ,please see bellow image.
Could you please align the value of every column to left or right , not to the center .

![layout_is_bad](https://user-images.githubusercontent.com/36788337/58222220-db7c0980-7d47-11e9-8d8a-d5c2bfe432f0.png)

**Comment by Nuke928** [comment]
This is because I don't cut long user names yet. A quick fix.

**Comment by Nuke928** [comment]
Done in https://github.com/Nuke928/NTop/commit/1d7c70724e9fe61808241b860adcee27aaa61c70
