### ISSUE TITLE
Feature Request: Chocolatey Package

### ISSUE THREAD

**Issue by rkttu-devsisters** [Nuke928/NTop#8]
I was very impressed with your tools. Can you release this tool so that it can be installed via Chocolatey Package Manager?

**Comment by Nuke928** [comment]
That's a splendid idea. Once I figure out how to make Chocolately packages I'll do it.

**Comment by Nuke928** [comment]
It's been submitted. Waiting for final review now https://chocolatey.org/packages/NTop.Portable/0.3.0

**Comment by Nuke928** [comment]
I wonder what's taking them so long :/

**Comment by Nuke928** [comment]
Approved.
